# if error with rakefile
# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fr6nk12/client-test -f ./client/Dockerfile.dev ./client
  # you can add another build command for testing another file

script:
 # If the command here produces an exit code anything other than 0
 # the the build has failed and travis file let us know.
 # NOTE: npm test does not by default exit. use "-- --coverage"
  - docker run -e CI=true fr6nk12/client-test npm test

after_success:
  # Once all the test succeed, go ahead and build the production images
  - docker build -t fr6nk12/multi-client ./client
  - docker build -t fr6nk12/multi-nginx ./nginx
  - docker build -t fr6nk12/multi-api ./api
  - docker build -t fr6nk12/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fr6nk12/multi-client
  - docker push fr6nk12/multi-nginx
  - docker push fr6nk12/multi-api
  - docker push fr6nk12/multi-worker

before_deploy:
  - gem install bundler
  - bundle update --bundler

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-029981135573'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY